
require 'rake/testtask'

TestModules = %w[
  Logger
  Core
  PCP
  HTTP
]

Configurations = %w[
  Debug
  Release
]

Configurations.each do |config|
  Rake::TestTask.new("test:#{config}") do |t|
    TestModules.each do |name|
      t.libs << "PeerCastStation.#{name}/bin/#{config}"
      t.libs << "Test#{name}"
      (t.pattern ||=[]) << "Test#{name}/test_*.rb"
    end
    t.verbose = true
  end
end

task :test => 'test:Debug'

