
require 'rake/testtask'

Rake::TestTask.new('test:Debug') do |t|
  t.libs << 'PeerCastStation.Core/bin/Debug'
  t.libs << 'PeerCastStation.PCP/bin/Debug'
  t.libs << 'TestCore'
  t.libs << 'TestPCP'
  t.test_files = FileList[
    'TestCore/*.rb',
    'TestPCP/*.rb',
  ]
  t.verbose = true
end

Rake::TestTask.new('test:Release') do |t|
  t.libs << 'PeerCastStation.Core/bin/Release'
  t.libs << 'PeerCastStation.PCP/bin/Release'
  t.libs << 'TestCore'
  t.libs << 'TestPCP'
  t.test_files = FileList[
    'TestCore/*.rb',
    'TestPCP/*.rb',
  ]
  t.verbose = true
end

